/* Generated by tools/generate.py from schema/vtp1.yaml. Do not edit. */
#ifndef VTP1_GENERATED_H
#define VTP1_GENERATED_H

#define VTP_MAJOR 1
#define VTP_MINOR 0
#define VTP_MIN_ATT_MTU 100

#define VTP_SERVICE_UUID "56545001-5f05-5b56-af87-dcab2baf2522"
#define VTP_CHAR_INFO_UUID "56544301-5f05-5b56-af87-dcab2baf2522"
#define VTP_CHAR_GPS_UUID "56544302-5f05-5b56-af87-dcab2baf2522"
#define VTP_CHAR_CAN_UUID "56544303-5f05-5b56-af87-dcab2baf2522"
#define VTP_CHAR_IMU_UUID "56544304-5f05-5b56-af87-dcab2baf2522"
#define VTP_CHAR_CONTROL_UUID "56544305-5f05-5b56-af87-dcab2baf2522"
#define VTP_CHAR_MONITOR_VALUES_UUID "56544306-5f05-5b56-af87-dcab2baf2522"
#define VTP_CHAR_AIDING_UUID "56544307-5f05-5b56-af87-dcab2baf2522"

/* Device self-description. Read once per connection; never cached across connections. */
#define VTP_INFO_SIZE 24
#define VTP_INFO_OFF_PROTOCOL_MAJOR 0
#define VTP_INFO_OFF_PROTOCOL_MINOR 1
#define VTP_INFO_OFF_CAPABILITIES 2
#define VTP_INFO_OFF_GPS_RATE_HZ 6
#define VTP_INFO_OFF_GPS_MAX_RATE_HZ 8
#define VTP_INFO_OFF_CAN_SUBSCRIPTION_SLOTS 10
#define VTP_INFO_OFF_CAN_MAX_FRAMES_PER_S 12
#define VTP_INFO_OFF_IMU_RATE_HZ 16
#define VTP_INFO_OFF_IMU_MAX_RATE_HZ 18
#define VTP_INFO_OFF_OBD_POLL_SLOTS 20
#define VTP_INFO_OFF_CLOCK_FLAGS 21
#define VTP_INFO_OFF_RESERVED_22 22

/* One complete position solution. Never split, never paired, never packed. */
#define VTP_GPS_FIX_SIZE 74
#define VTP_GPS_FIX_OFF_SEQ 0
#define VTP_GPS_FIX_OFF_DROPPED 2
#define VTP_GPS_FIX_OFF_VALIDITY 4
#define VTP_GPS_FIX_OFF_T_DEVICE 8
#define VTP_GPS_FIX_OFF_T_UTC 16
#define VTP_GPS_FIX_OFF_LAT 24
#define VTP_GPS_FIX_OFF_LON 28
#define VTP_GPS_FIX_OFF_ALT_MSL 32
#define VTP_GPS_FIX_OFF_ALT_ELLIPSOID 36
#define VTP_GPS_FIX_OFF_VEL_N 40
#define VTP_GPS_FIX_OFF_VEL_E 44
#define VTP_GPS_FIX_OFF_VEL_D 48
#define VTP_GPS_FIX_OFF_HEAD_MOT 52
#define VTP_GPS_FIX_OFF_H_ACC 56
#define VTP_GPS_FIX_OFF_V_ACC 60
#define VTP_GPS_FIX_OFF_S_ACC 64
#define VTP_GPS_FIX_OFF_P_DOP 68
#define VTP_GPS_FIX_OFF_FIX_TYPE 70
#define VTP_GPS_FIX_OFF_NUM_SV 71
#define VTP_GPS_FIX_OFF_FIX_FLAGS 72
#define VTP_GPS_FIX_OFF_EXT_COUNT 73

/* Batch header. Followed by `count` can_record entries. */
#define VTP_CAN_HEADER_SIZE 16
#define VTP_CAN_HEADER_OFF_SEQ 0
#define VTP_CAN_HEADER_OFF_DROPPED 2
#define VTP_CAN_HEADER_OFF_T_BASE 4
#define VTP_CAN_HEADER_OFF_COUNT 12
#define VTP_CAN_HEADER_OFF_FLAGS 13
#define VTP_CAN_HEADER_OFF_RESERVED 14

/* One CAN frame with a device-measured bus-arrival time. */
#define VTP_CAN_RECORD_SIZE 7
#define VTP_CAN_RECORD_OFF_DT 0
#define VTP_CAN_RECORD_OFF_ID 2
#define VTP_CAN_RECORD_OFF_LEN 6

/* Batch header. Followed by `count` evenly spaced imu_sample entries. */
#define VTP_IMU_HEADER_SIZE 20
#define VTP_IMU_HEADER_OFF_SEQ 0
#define VTP_IMU_HEADER_OFF_DROPPED 2
#define VTP_IMU_HEADER_OFF_T_BASE 4
#define VTP_IMU_HEADER_OFF_PERIOD 12
#define VTP_IMU_HEADER_OFF_COUNT 16
#define VTP_IMU_HEADER_OFF_FLAGS 17
#define VTP_IMU_HEADER_OFF_RESERVED 18

/* Sensor-frame acceleration and rotation. Vehicle alignment is the client's job. */
#define VTP_IMU_SAMPLE_SIZE 12
#define VTP_IMU_SAMPLE_OFF_AX 0
#define VTP_IMU_SAMPLE_OFF_AY 2
#define VTP_IMU_SAMPLE_OFF_AZ 4
#define VTP_IMU_SAMPLE_OFF_GX 6
#define VTP_IMU_SAMPLE_OFF_GY 8
#define VTP_IMU_SAMPLE_OFF_GZ 10

/* Every channel this device asks the client to supply. Followed by `count` monitor_channel entries. */
#define VTP_MONITOR_DECLARATION_SIZE 2
#define VTP_MONITOR_DECLARATION_OFF_COUNT 0
#define VTP_MONITOR_DECLARATION_OFF_RESERVED 1

/* One channel a device asks the client to supply. */
#define VTP_MONITOR_CHANNEL_SIZE 4
#define VTP_MONITOR_CHANNEL_OFF_SLOT 0
#define VTP_MONITOR_CHANNEL_OFF_CHANNEL 1
#define VTP_MONITOR_CHANNEL_OFF_MAX_AGE 3

/* Batch header for a client-to-device value update. Followed by `count` monitor_value entries. */
#define VTP_MONITOR_HEADER_SIZE 4
#define VTP_MONITOR_HEADER_OFF_SEQ 0
#define VTP_MONITOR_HEADER_OFF_COUNT 2
#define VTP_MONITOR_HEADER_OFF_RESERVED 3

/* One value for a slot the device asked for. */
#define VTP_MONITOR_VALUE_SIZE 6
#define VTP_MONITOR_VALUE_OFF_SLOT 0
#define VTP_MONITOR_VALUE_OFF_VALIDITY 1
#define VTP_MONITOR_VALUE_OFF_VALUE 2

/* The envelope of every Control response. Detail follows only when status is ok. */
#define VTP_CONTROL_RESPONSE_SIZE 3
#define VTP_CONTROL_RESPONSE_OFF_OPCODE 0
#define VTP_CONTROL_RESPONSE_OFF_TAG 1
#define VTP_CONTROL_RESPONSE_OFF_STATUS 2

/* The detail of a TIME_SYNC response. Two readings of one clock, so a client can bound its own error. */
#define VTP_TIME_SYNC_SIZE 16
#define VTP_TIME_SYNC_OFF_T_DEVICE_RX 0
#define VTP_TIME_SYNC_OFF_T_DEVICE_TX 8

/* The detail of a GET_POWER response. What the device knows about its own supply, and no more. */
#define VTP_POWER_STATE_SIZE 4
#define VTP_POWER_STATE_OFF_VALIDITY 0
#define VTP_POWER_STATE_OFF_SOURCE 1
#define VTP_POWER_STATE_OFF_PERCENT 2
#define VTP_POWER_STATE_OFF_RESERVED 3

/* What aiding this device accepts, and what it already holds. */
#define VTP_GNSS_AID_CAPS_SIZE 16
#define VTP_GNSS_AID_CAPS_OFF_VALIDITY 0
#define VTP_GNSS_AID_CAPS_OFF_FORMAT 1
#define VTP_GNSS_AID_CAPS_OFF_RESERVED_2 2
#define VTP_GNSS_AID_CAPS_OFF_MAX_BYTES 4
#define VTP_GNSS_AID_CAPS_OFF_HELD_UNTIL 8

/* The detail of a GNSS_AID_BEGIN response. Opens a transfer and fixes its chunking. */
#define VTP_AID_BEGIN_RESULT_SIZE 4
#define VTP_AID_BEGIN_RESULT_OFF_TOKEN 0
#define VTP_AID_BEGIN_RESULT_OFF_CHUNK_BYTES 1
#define VTP_AID_BEGIN_RESULT_OFF_RESERVED_3 3

/* One chunk of an aiding transfer, written without a response. */
#define VTP_AID_CHUNK_SIZE 3
#define VTP_AID_CHUNK_OFF_TOKEN 0
#define VTP_AID_CHUNK_OFF_INDEX 1

/* The detail of a GNSS_AID_COMMIT response. What became of the transfer. */
#define VTP_AID_COMMIT_RESULT_SIZE 4
#define VTP_AID_COMMIT_RESULT_OFF_VALIDITY 0
#define VTP_AID_COMMIT_RESULT_OFF_RESULT 1
#define VTP_AID_COMMIT_RESULT_OFF_FIRST_MISSING 2

/* The detail of an OBD_INFO response. What the car answered, measured when asked. Followed by `count` obd_ecu entries. */
#define VTP_OBD_PROBE_SIZE 20
#define VTP_OBD_PROBE_OFF_VALIDITY 0
#define VTP_OBD_PROBE_OFF_COUNT 1
#define VTP_OBD_PROBE_OFF_REQUEST_ID 2
#define VTP_OBD_PROBE_OFF_SUPPORTED_01_20 6
#define VTP_OBD_PROBE_OFF_SUPPORTED_21_40 10
#define VTP_OBD_PROBE_OFF_SUPPORTED_41_60 14
#define VTP_OBD_PROBE_OFF_RESERVED_18 18

/* One ECU that answered the probe, named by the identifier it responds on. */
#define VTP_OBD_ECU_SIZE 4
#define VTP_OBD_ECU_OFF_ID 0

typedef enum {
    VTP_FIX_TYPE_NONE = 0,
    VTP_FIX_TYPE_DEAD_RECKON = 1,
    VTP_FIX_TYPE_FIX_2D = 2,
    VTP_FIX_TYPE_FIX_3D = 3,
    VTP_FIX_TYPE_GNSS_DR = 4,
    VTP_FIX_TYPE_TIME_ONLY = 5,
} vtp_fix_type_t;

typedef enum {
    VTP_STATUS_OK = 0,
    VTP_STATUS_UNSUPPORTED_OPCODE = 1,
    VTP_STATUS_BAD_PARAMS = 2,
    VTP_STATUS_TABLE_FULL = 3,
    VTP_STATUS_RATE_EXCEEDED = 4,
    VTP_STATUS_BUSY = 5,
    VTP_STATUS_NEEDS_ENCRYPTION = 6,
    VTP_STATUS_UNKNOWN_SUBSCRIPTION = 7,
} vtp_status_t;

typedef enum {
    VTP_SUB_MODE_EVERY_FRAME = 0,
    VTP_SUB_MODE_PERIODIC = 1,
} vtp_sub_mode_t;

typedef enum {
    VTP_CHANNEL_LAP_TIME = 1,
    VTP_CHANNEL_LAST_LAP_TIME = 2,
    VTP_CHANNEL_BEST_LAP_TIME = 3,
    VTP_CHANNEL_DELTA_BEST = 4,
    VTP_CHANNEL_PREDICTED_LAP_TIME = 5,
    VTP_CHANNEL_LAP_NUMBER = 6,
    VTP_CHANNEL_SPEED = 7,
    VTP_CHANNEL_SESSION_DISTANCE = 8,
    VTP_CHANNEL_SESSION_TIME = 9,
} vtp_channel_t;

typedef enum {
    VTP_POWER_SOURCE_EXTERNAL = 1,
    VTP_POWER_SOURCE_DISCHARGING = 2,
    VTP_POWER_SOURCE_CHARGING = 3,
    VTP_POWER_SOURCE_CHARGED = 4,
} vtp_power_source_t;

typedef enum {
    VTP_AID_FORMAT_UBX_MGA = 1,
} vtp_aid_format_t;

typedef enum {
    VTP_AID_RESULT_APPLIED = 1,
    VTP_AID_RESULT_INCOMPLETE = 2,
    VTP_AID_RESULT_BAD_CRC = 3,
    VTP_AID_RESULT_REJECTED = 4,
} vtp_aid_result_t;

#define VTP_GPS_VALIDITY_T_UTC (1u << 0)
#define VTP_GPS_VALIDITY_T_UTC_RESOLVED (1u << 1)
#define VTP_GPS_VALIDITY_POSITION (1u << 2)
#define VTP_GPS_VALIDITY_ALT_MSL (1u << 3)
#define VTP_GPS_VALIDITY_ALT_ELLIPSOID (1u << 4)
#define VTP_GPS_VALIDITY_VELOCITY (1u << 5)
#define VTP_GPS_VALIDITY_HEAD_MOT (1u << 6)
#define VTP_GPS_VALIDITY_H_ACC (1u << 7)
#define VTP_GPS_VALIDITY_V_ACC (1u << 8)
#define VTP_GPS_VALIDITY_S_ACC (1u << 9)
#define VTP_GPS_VALIDITY_P_DOP (1u << 10)
#define VTP_GPS_VALIDITY_NUM_SV (1u << 11)
#define VTP_GPS_VALIDITY_RESERVED 0xFFFFF000u
#define VTP_GPS_VALIDITY_KNOWN (~(uint32_t)VTP_GPS_VALIDITY_RESERVED)

#define VTP_FIX_FLAGS_DIFFERENTIAL (1u << 0)
#define VTP_FIX_FLAGS_RTK_FLOAT (1u << 1)
#define VTP_FIX_FLAGS_RTK_FIXED (1u << 2)
#define VTP_FIX_FLAGS_CLOCK_DISCIPLINED (1u << 3)
#define VTP_FIX_FLAGS_SOLUTION_EPOCH (1u << 4)
#define VTP_FIX_FLAGS_RESERVED 0xE0u
#define VTP_FIX_FLAGS_KNOWN (~(uint32_t)VTP_FIX_FLAGS_RESERVED)

#define VTP_CAPABILITIES_GPS (1u << 0)
#define VTP_CAPABILITIES_CAN (1u << 1)
#define VTP_CAPABILITIES_IMU (1u << 2)
#define VTP_CAPABILITIES_MONITOR (1u << 3)
#define VTP_CAPABILITIES_CONTROL (1u << 4)
#define VTP_CAPABILITIES_CAN_FD (1u << 5)
#define VTP_CAPABILITIES_MASKED_SUBSCRIPTIONS (1u << 6)
#define VTP_CAPABILITIES_POWER (1u << 8)
#define VTP_CAPABILITIES_GNSS_AIDING (1u << 9)
#define VTP_CAPABILITIES_OBD (1u << 10)
#define VTP_CAPABILITIES_RESERVED 0xFFFFF880u
#define VTP_CAPABILITIES_KNOWN (~(uint32_t)VTP_CAPABILITIES_RESERVED)

#define VTP_CAN_FLAGS_SHEDDING (1u << 0)
#define VTP_CAN_FLAGS_POLLING (1u << 1)
#define VTP_CAN_FLAGS_RESERVED 0xFCu
#define VTP_CAN_FLAGS_KNOWN (~(uint32_t)VTP_CAN_FLAGS_RESERVED)

#define VTP_IMU_FLAGS_ACCEL (1u << 0)
#define VTP_IMU_FLAGS_GYRO (1u << 1)
#define VTP_IMU_FLAGS_SATURATED (1u << 2)
#define VTP_IMU_FLAGS_RESERVED 0xF8u
#define VTP_IMU_FLAGS_KNOWN (~(uint32_t)VTP_IMU_FLAGS_RESERVED)

#define VTP_CLOCK_FLAGS_GNSS_DISCIPLINED (1u << 0)
#define VTP_CLOCK_FLAGS_SURVIVES_RECONNECT (1u << 1)
#define VTP_CLOCK_FLAGS_RESERVED 0xFCu
#define VTP_CLOCK_FLAGS_KNOWN (~(uint32_t)VTP_CLOCK_FLAGS_RESERVED)

#define VTP_MONITOR_VALIDITY_PRESENT (1u << 0)
#define VTP_MONITOR_VALIDITY_RESERVED 0xFEu
#define VTP_MONITOR_VALIDITY_KNOWN (~(uint32_t)VTP_MONITOR_VALIDITY_RESERVED)

#define VTP_POWER_VALIDITY_SOURCE (1u << 0)
#define VTP_POWER_VALIDITY_PERCENT (1u << 1)
#define VTP_POWER_VALIDITY_RESERVED 0xFCu
#define VTP_POWER_VALIDITY_KNOWN (~(uint32_t)VTP_POWER_VALIDITY_RESERVED)

#define VTP_AID_VALIDITY_HELD_UNTIL (1u << 0)
#define VTP_AID_VALIDITY_RESERVED 0xFEu
#define VTP_AID_VALIDITY_KNOWN (~(uint32_t)VTP_AID_VALIDITY_RESERVED)

#define VTP_COMMIT_VALIDITY_FIRST_MISSING (1u << 0)
#define VTP_COMMIT_VALIDITY_RESERVED 0xFEu
#define VTP_COMMIT_VALIDITY_KNOWN (~(uint32_t)VTP_COMMIT_VALIDITY_RESERVED)

#define VTP_OBD_VALIDITY_RESPONDED (1u << 0)
#define VTP_OBD_VALIDITY_RESERVED 0xFEu
#define VTP_OBD_VALIDITY_KNOWN (~(uint32_t)VTP_OBD_VALIDITY_RESERVED)

/* SPEC.md 4.1 -- a capability bit and every bit it requires. */
typedef struct { uint32_t bit, requires_; const char *name; } vtp_capability_rule_t;
#define VTP_CAPABILITY_RULES { \
    { (1u << 0), 0x00000000u, "gps" }, \
    { (1u << 1), 0x00000010u, "can" }, \
    { (1u << 2), 0x00000000u, "imu" }, \
    { (1u << 3), 0x00000010u, "monitor" }, \
    { (1u << 4), 0x00000000u, "control" }, \
    { (1u << 5), 0x00000002u, "can_fd" }, \
    { (1u << 6), 0x00000002u, "masked_subscriptions" }, \
    { (1u << 8), 0x00000010u, "power" }, \
    { (1u << 9), 0x00000011u, "gnss_aiding" }, \
    { (1u << 10), 0x00000012u, "obd" }, \
}
#define VTP_CAPABILITY_RULE_COUNT 10

/* SPEC.md 4.1 -- info fields that MUST be zero when their
 * capability bit is clear. Offset and size, so one loop covers all. */
typedef struct { uint32_t bit; uint8_t offset, size; const char *field; } vtp_capacity_rule_t;
#define VTP_CAPACITY_RULES { \
    { (1u << 0), 6, 2, "gps_rate_hz" }, \
    { (1u << 0), 8, 2, "gps_max_rate_hz" }, \
    { (1u << 1), 10, 2, "can_subscription_slots" }, \
    { (1u << 1), 12, 4, "can_max_frames_per_s" }, \
    { (1u << 2), 16, 2, "imu_rate_hz" }, \
    { (1u << 2), 18, 2, "imu_max_rate_hz" }, \
    { (1u << 10), 20, 1, "obd_poll_slots" }, \
}
#define VTP_CAPACITY_RULE_COUNT 7

/* SPEC.md 15 -- capacities that MUST be NON-zero while their
 * bit is SET. Same row type as VTP_CAPACITY_RULES. */
#define VTP_CAPACITY_REQUIRED_RULES { \
    { (1u << 10), 20, 1, "obd_poll_slots" }, \
}
#define VTP_CAPACITY_REQUIRED_RULE_COUNT 1

#endif /* VTP1_GENERATED_H */
